version: "3.7"

volumes:
  local_pgdata: {}

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: express_server:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./src:/usr/src/app/src
    command: pnpm start:dev
  postgres:
    container_name: postgres
    image: postgres:16.3
    restart: always
    env_file:
      - .env
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer:4.8.1
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
